--[[ ----------------------------------------------------------------------------------------------
 File       : bind_smart_terrain.script
 Description: Smart terrain binder (Нужен для того, чтобы серверный объект smart terrain получал обновления)
 Copyright  : 2004 © GSC Game World
 Author     : Чугай Александр
 Editors    : Karlan
--]] ----------------------------------------------------------------------------------------------
--//-----------------------------------------------------------------
--// Flags for enable output of the debug information
--//-----------------------------------------------------------------
_DEBUG_ = false --// file under debugging?
_DEBUG_GSC_ = _DEBUG_ and false --// only for scripts by GSC
--//-----------------------------------------------------------------
function bind(obj)
    local ini = obj:spawn_ini()
    if sim and ini and (ini:section_exist("smart_terrain") or ini:section_exist("gulag1")) then
        if obj:clsid() == clsid.smart_terrain then
            obj:bind_object(smart_terrain_binder(obj))
        else
            abort("bind:You must use SMART TERRAIN instead of SCRIPT ZONE=[%s]", obj:name() )
        end
    end
end
--//-----------------------------------------------------------------
class "smart_terrain_binder" ( object_binder )
--//-----------------------------------------------------------------
function smart_terrain_binder:__init(obj) super(obj)
end
----------------------------------------------------------------------------------------------------------------------
function smart_terrain_binder:net_spawn( server_object )
    if not object_binder.net_spawn( self, server_object ) then
        warning("net_spawn:object=NIL")
        return false
    end
    --// получить ссылку на настоящий серверный объект
    self.se_smart_terrain = server_object.id and alife():object(server_object.id)
    if not self.se_smart_terrain then
        warning("net_spawn:se_smart_terrain=NIL")
        return true
    end
    db.add_zone(self.object)
    return true
end
----------------------------------------------------------------------------------------------------------------------
function smart_terrain_binder:net_destroy()
    db.del_zone(self.object)
    db.storage[self.object:id()] = nil
end
----------------------------------------------------------------------------------------------------------------------
function smart_terrain_binder:net_Relcase(obj)
    if self.se_smart_terrain and self.se_smart_terrain.npc_info[obj:id()] then
        self.se_smart_terrain.gulag:object_setup_offline(obj:id(), true)
    end
end
----------------------------------------------------------------------------------------------------------------------
function smart_terrain_binder:update( delta )
    self.se_smart_terrain:update()
end
----------------------------------------------------------------------------------------------------------------------